### ISSUE TITLE
Interpreting latent spaces from autoencoders

### ISSUE THREAD

**Issue by jessegmeyerlab** [iancovert/sage#34]
In the case where you do not have a y_true as requested by SAGE, for example when you are trying to use SAGE to interpret latent spaces produced by autoencoders, can you think of any reason why it would not be appropriate to use the predicted values of the latent space?

**Comment by iancovert** [comment]
Hi, sorry I'm not sure I understand the question. In your problem, which inputs are you trying to interpret and what are the corresponding outputs? It sounds like you're perhaps thinking to interpret the raw inputs to the AE, and you're thinking of the latent encoding as the output? I've seen people do things like this before with AEs but I'm not sure what you're interested in learning from it.

**Comment by jgmeyerucsd** [comment]
Thanks for your quick response. 

Yes exactly, using SAGE to interpret the latent space as output given the full inputs. For example, see figure 3 of this paper.

https://www.nature.com/articles/s42003-022-03579-3

As an example from this paper, one question we would like to understand how inputs are grouping themselves in the latent space. Do certain metabolites group together in their importance in the latent space?

Specifically Caleb and I were discussing whether SAGE (and SHAP) care about the true values or whether the interpretation is in reference to the prediction without regard to its accuracy. The reason this is more important when interpreting the latent space is that there is no truth and no sense of error.

**Comment by iancovert** [comment]
I see, thanks for pointing me to their figure. I don't have a lot of familiarity with interpreting pathways, but this idea of finding influential groups of inputs seems to make sense.

For the question about whether SAGE/SHAP care about the true value / correct prediction, I would summarize it like this:

- SHAP has no way to account for the true prediction. It only quantifies how the model output $f(x)$ varies as different inputs are removed, and it does so for a single prediction at a time (hence "local")
- SAGE is meant to quantify how the loss/accuracy change as different inputs are removed, and it does so across a dataset of inputs/predictions (hence "global"). For this it requires true labels
- SAGE can alternatively be run without labels by substituting the full model prediction $f(x)$ for the label $Y$. This usage has roots in some earlier works, which we discuss in Appendix F of our [paper](https://arxiv.org/pdf/2004.00668): in this case, SAGE should be interpreted as measuring which inputs have the strongest influence on the prediction. As you might imagine, these two versions of SAGE coincide when there is a $Y$ and the model $f$ is optimal

It sounds like you have a decent understanding of SHAP/SAGE, but in case it's helpful for anyone in your group we wrote this [blog post](https://iancovert.com/blog/understanding-shap-sage/) a while back as a primer on both methods.

**Comment by jessegmeyerlab** [comment]
thanks!
